infection_reporter/data_reporter/urls.py
from django.conf.urls import url

from data_reporter.views import get_human_cases, get_animal_cases, index, get_disease_view

urlpatterns = [
    url(r'index/', index, name='index'),
    url(r'disease/(?P<disease_pk>\d+)/$', get_disease_view, name='disease'),
    url(r'human/cases/(?P<disease_pk>\d+)/$', get_human_cases, name='human-cases'),
    url(r'animal/cases/(?P<disease_pk>\d+)/$', get_animal_cases, name='animal-cases'),
]

infection_reporter/infection_reporter/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import data_reporter
from data_reporter import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^data-reporter/', include(data_reporter.urls, namespace='data-reporter'))
]

infection_reporter/data_reporter/models.py
from django.db import models


# Create your models here.
class StdModel(models.Model):
    class Meta:
        app_label = 'data_reporter'
        abstract = True


class Disease(StdModel):
    class Meta:
        db_table = 'disease'
        verbose_name = 'Disease'
        verbose_name_plural = 'Disease'
        ordering = ['name']

    name = models.CharField('Name', max_length=255)
    incubation_period = models.PositiveIntegerField('Incubation period')
    symptoms = models.CharField('Symptoms', max_length=255)
    sequela = models.BooleanField('Sequela', default=False)
    human = models.BooleanField('Human', default=False)
    animal = models.BooleanField('Animal', default=False)
    urgent = models.BooleanField('Alarm', default=False)

    def __str__(self):
        return self.name


class HumanCase(StdModel):
    class Meta:
        db_table = 'human_case'
        verbose_name = 'Human Case'
        verbose_name_plural = 'Human Cases'

    case_count = models.PositiveIntegerField('Number of cases')
    hospitalization_avg = models.DecimalField('Hospitalization average time ', decimal_places=1, max_digits=3)
    sampling_avg = models.DecimalField('Sampling average time', decimal_places=1, max_digits=3)
    laboratory_avg = models.DecimalField('Laboratory average time', decimal_places=1, max_digits=3)
    report_avg = models.DecimalField('Report average time', decimal_places=1, max_digits=3)
    treatment_avg = models.DecimalField('Treatment average time', decimal_places=1, max_digits=3)
    district = models.CharField('District', max_length=255)
    village = models.CharField('Village', max_length=255)
    min_age = models.DecimalField('Min. Age', decimal_places=1, max_digits=4)
    max_age = models.DecimalField('Max Age', decimal_places=1, max_digits=4)
    age_avg = models.DecimalField('Average Age', decimal_places=1, max_digits=4)
    vaccination_rate = models.DecimalField('Vaccination Rate', decimal_places=1, max_digits=4)
    death_rate = models.DecimalField('Death Rate', decimal_places=1, max_digits=4)
    recovery_rate = models.DecimalField('Recovery Rate', decimal_places=1, max_digits=4)
    sequela_rate = models.DecimalField('Sequela Rate', decimal_places=1, max_digits=4)
    attack_rate = models.DecimalField('Attack Rate', decimal_places=1, max_digits=4)
    disease = models.ForeignKey(Disease, related_name='human_cases')

    def __str__(self):
        return "{} - {} - {}".format(self.disease, self.case_count, self.district)


class AnimalCase(StdModel):
    class Meta:
        db_table = 'animal_case'
        verbose_name = 'Animal Case'
        verbose_name_plural = 'Animal Cases'

    case_count = models.PositiveIntegerField('Number of cases')
    district = models.CharField('District', max_length=255)
    village = models.CharField('Village', max_length=255)
    morbidity_rate = models.DecimalField('Morbidity rate', max_digits=4, decimal_places=1)
    mortality_rate = models.DecimalField('Mortality rate', max_digits=4, decimal_places=1)
    fatality_rate = models.DecimalField('Fatality rate', max_digits=4, decimal_places=1)
    disease = models.ForeignKey(Disease, related_name='animal_cases')

    def __str__(self):
        return "{} - {} - {}".format(self.disease, self.case_count, self.district)

infection_reporter/data_reporter/views.py
from django.core.mail import EmailMessage
from django.http import JsonResponse
from django.shortcuts import render

from data_reporter.models import HumanCase, AnimalCase, Disease
from data_reporter.serializers import HumanCaseSerializer, AnimalCaseSerializer


def index(request):
    return render(request, 'data_reporter/index.html')


def get_disease_view(request, disease_pk):
    disease = Disease.objects.get(pk=disease_pk)
    return render(request, 'data_reporter/index.html', context={'active': disease.name})


def get_human_cases(request, disease_pk):
    human_cases = HumanCase.objects.filter(disease_id=disease_pk)
    return JsonResponse({'data': HumanCaseSerializer(human_cases, many=True).data})


def get_animal_cases(request, disease_pk):
    human_cases = AnimalCase.objects.filter(disease_id=disease_pk)
    return JsonResponse({'data': AnimalCaseSerializer(human_cases, many=True).data})

infection_reporter/data_reporter/templates/data_reporter/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">


    <title>Alert and Alarm Dashboard</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'data_reporter/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'data_reporter/css/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'data_reporter/css/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'data_reporter/css/messenger.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'data_reporter/css/messenger-theme-future.css' %}">

    <script type="text/javascript" language="javascript" src="{% static 'data_reporter/js/jquery.min.js' %}"></script>
    <script type="text/javascript" language="javascript"
            src="{% static 'data_reporter/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" language="javascript"
            src="{% static 'data_reporter/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" language="javascript"
            src="{% static 'data_reporter/js/dataTables.bootstrap.min.js' %}">
    </script>
    <script type="text/javascript" src="{% static 'data_reporter/js/messenger.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'data_reporter/js/messenger-theme-future.js' %}"></script>
    <script type="text/javascript" src="{% static 'data_reporter/js/index.js' %}"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><i class="glyphicon glyphicon-bullhorn" style="color: red"></i> Alarm
                    and Alert</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a id="add-human-case" href="#">+ Normal Case</a></li>
                    <li><a id="add-animal-case" href="#">+ Outbreak Case</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
</header>
<div class="row">
    <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked">
            {% for disease in diseases %}
                <li {% ifequal active disease.name %} class="active"
                                                      data-disease-id="{{ disease.id }}" {% endifequal %}>
                    <a href="{% url 'data-reporter:disease' disease.id %}">{{ disease.name }}
                        <span class="badge pull-right">{{ disease.human_cases.count }} | {{ disease.animal_cases.count }}</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-md-10">
        <ul class="nav nav-tabs" role="tablist">
            <li class="active">
                <a href="#human-cases-tab" data-toggle="tab"><i class="glyphicon glyphicon-user"></i> Human</a>
            </li>
            <li>
                <a href="#animal-cases-tab" data-toggle="tab"><i class="glyphicon glyphicon-knight"></i> Animal</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="human-cases-tab">
                <table id="human-cases-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Cases</th>
                        <th>Disease</th>
                        <th>District</th>
                        <th>Village</th>
                        <th>Report avg.</th>
                        <th>Hosp. avg.</th>
                        <th>Sampling avg.</th>
                        <th>Lab. avg.</th>
                        <th>Treatment avg.</th>
                        <th>Min Age</th>
                        <th>Max Age</th>
                        <th>Age avg.</th>
                        <th>Vaccination rate</th>
                        <th>Death rate</th>
                        <th>Recovery rate</th>
                        <th>Sequela rate</th>
                        <th>Attack rate</th>
                    </tr>
                    </thead>
                </table>
            </div>
            <div class="tab-pane" id="animal-cases-tab">
                <table id="animal-cases-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                    <tr>
                        <th>Cases</th>
                        <th>Disease</th>
                        <th>District</th>
                        <th>Village</th>
                        <th>Morbidity rate</th>
                        <th>Mortality rate</th>
                        <th>Fatality rate</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
</body>
</html>